1) all the 3 dimensional arrays
2) datatypes in array and concepts of downcasting and upcasting
3) converting list, sets, tuple, dictionary to ndarray
4) creating nd array from scratch with zeros , ones , empty and full
5) copying shapes from another array
6) generating random values
7) range function in nd array
8) linspace and logspace to evenly divide datapoints within a range 
9) diagonal, identity matrix
10) indexing
11) slicing and copying slice of an array
12) advanced indexing

In [3]:
# array
import numpy as np
# 1d array 
arr1 = np.array([1,2,3,4,5])


# 2d array 
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

# 3d array
arr3 = np.array([
                # 1st floor
               [[1,2,3], # 1st row
                [4,5,6], # 2nd row
                [7,8,9]], # 3rd row

                # 2nd floor
                [[1,2,3], # 1st row
                [4,5,6], # 2nd row
                [7,8,9]] # 3rd row

                 
])

# dimension 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim) 


#shape 
print(arr1.shape)
print(arr2.shape)
print(arr3.shape) 


#data type 
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size 
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(2, 3, 3)
int64
int64
int64
5
6
18


In [ ]:
# datatypes in array downcasting and upcasting


import numpy as np

arr = np.array([1,2,3.2]) 
# upcasted to float 
print(arr.dtype) 

#upcasted to string
arr = np.array([1,2,3.2,'hello']) 
print(arr.dtype) 


arr = np.array([1,True,3.25,'hello',]) 
print(arr.dtype) 

# downcasting
arr = np.array([1,2,300],dtype=np.int16) # downcasted to int16 data type
print(arr.dtype)
print(arr)


float64
<U32
<U32


In [ ]:
# here datatype will be converted to float as max datatype is float
import numpy as np

lst = [10,20,30,40 , 40.5] 

arr = np.array(lst) 

print(arr) 
print(type(arr)) 
print(arr.dtype) 

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
float64


In [ ]:
# here datatype will be converted to int32 as we are forcing it to int32

import numpy as np
lst = [10,20,30,40 , 40.5] 

arr = np.array(lst, dtype=np.int32) 

print(arr) 
print(type(arr)) 
print(arr.dtype) 

In [ ]:
# here datatype will be converted to string as max datatype is string
import numpy as np

mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst) 

print(arr) 
print(type(arr)) 
print(arr.dtype) 

In [ ]:
# converting tuple to ndarray and changing datatype
import numpy as np

tpl = (10,20,30) 

arr = np.array(tpl) # default datatype is int32 or int64 based on system
print(arr.dtype) 
arr = arr.astype(np.int16) # converting to int16 datatype
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

int64
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [7]:
# converting set to ndarray but set is converted to list first because set is unordered
import numpy as np
st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [ ]:
# converting dictionary to ndarray but dictionary is converted to list of items first

import numpy as np
dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

items = dc.items() # accessing items of dictionary

arr = np.array(list(items)) # converting to list of items and then to ndarray
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


In [17]:
# creating nd array from scratch with zeros , ones , empty and full
import numpy as np

array = np.zeros((3,4)) # 3 rows and 4 columns
print(array)
print(array.shape)
print(array.dtype)
print(array.ndim)



arr_1 = np.ones((2,3) , dtype=np.int16) # 2 rows and 3 columns
print(arr_1)



arr_2 = np.empty((2,3)) # 2 rows and 3 columns
print(arr_2)



arr_3 = np.full((2,3) , 7) # 2 rows and 3 columns , filled with 7
print(arr_3)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
float64
2
[[1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]


In [ ]:
# copying shape from another array
import numpy as np

arr3 = np.array([
                # 1st floor
               [[1,2,3], # 1st row
                [4,5,6], # 2nd row
                [7,8,9]], # 3rd row

                # 2nd floor
                [[1,2,3], # 1st row
                [4,5,6], # 2nd row
                [7,8,9]] # 3rd row

                 
])


arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)




[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
(2, 3, 3)
int64
3


In [ ]:
# random values in nd array

import numpy as np

# random values in nd array with rand values between 0 and 1 by default
arr = np.random.rand(2,3) # np.random.rand(shape)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


# random values in nd array with int datatype within a range
arr = np.random.randint(10, 50 , size = (3,4)) # np.random.randint(low , high , size = (rows , columns))    
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


# random values in nd array with float datatype within a range
arr = np.random.uniform(50,100, (3,3,4))   # np.random.uniform(low , high , size = (dim1, dim2, dim3))

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.09832678 0.13293195 0.94119277]
 [0.18487672 0.972768   0.36062747]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [22]:
#  range of values in nd array with arange (same as range function but returns nd array)
import numpy as np

arr = np.arange(1, 10, 3) # np.arange(start , end , step)
mat = arr.reshape((3,1)) # reshaping to 3 rows and 1 column

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

print(mat)

[1 4 7]
<class 'numpy.ndarray'>
int64
(3,)
1
3
[[1]
 [4]
 [7]]


In [ ]:
# linspace to evenly divide datapoints within a range 
import numpy as np

arr = np.linspace(1, 10, 10) # np.linspace(start , end , number of datapoints)
print(arr)

arr_2 = np.linspace(1, 10, 11) # 11 datapoints from 1 to 10
print(arr_2)

arr_3 = np.linspace(1, 10 , 5) # 5 datapoints from 1 to 10
print(arr_3)




[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# logspace to evenly divide datapoints within a range in log scale it takes log base 10 by default
import numpy as np

arr = np.logspace(1, 4, 4) # np.logspace(start , end , number of datapoints)
print(arr) # here 10^1 , 10^2 , 10^3 , 10^4 , here the start end represent the power of 10

arr_2 = np.logspace(0, 4, 6) # here 10^0 , 10^0.8 , 10^1.6 , 10^2.4 , 10^3.2 , 10^4
print(arr_2)  

arr_3 = np.logspace(0, 4, 6 , base=2) # here 2^0 , 2^0.8 , 2^1.6 , 2^2.4 , 2^3.2 , 2^4
print(arr_3)

[   10.   100.  1000. 10000.]
[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


In [34]:
#  creating matrix for linear algebra

# diagonal_matrix = np.diag([1,2,3]) 
diagonal_matrix = np.diag([1,2,3]) # creating diagonal matrix with diagonal elements 1,2,3
print(diagonal_matrix)


# identity matrix = np.eye(n) where n is number of rows and columns
identity_matrix = np.eye(4) # creating 4x4 identity matrix
print(identity_matrix)


# identity matrix = np.eye(rows, columns)
identity_matrix_1 = np.eye(3,4) # creating 3x4 identity matrix
print(identity_matrix_1)


# identity matrix = np.eye(rows, columns, k) where k is the diagonal shift
identity_matrix_2 = np.eye(3,4,-1) # creating 3x4 identity matrix with diagonal shifted to left by 1
print(identity_matrix_2)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
# indexing 

import numpy as np
arr = np.array([10,20,30,40,50])

print(arr[1]) # accessing 2nd element
print(arr[1] = 100) # modifying 2nd element



arr_2 = np.array([
    [10,20,30], 
    [40,50,60],
    [70,80,90]])

print(arr_2[1,2]) # accessing element at 2nd row and 3rd column

In [ ]:
# slicing

import numpy as np

arr = np.array([10,20,30,40,50])
print(arr[1:4]) # slicing from index 1 to index 3


# 2d array slicing = arr_2[row_start: row_end: step , col_start: col_end: step]

arr_2 = np.array([ 
                  [1,2,3], 
                  [4,5,6] 
                ])
# getting row
print(arr_2[0:1 ,]) # accessing first row and all columns
print(arr_2[1: , ]) # accessing from 2nd row to end all columns

# getting column
print(arr_2[ :: , 0:1]) # accessing first column
print(arr_2[ :: , 1:2]) # accessing second column
print(arr_2[ :: , 0:2]) # accessing first two columns

[20 30 40]
[[1 2 3]]
[[4 5 6]]
[[1]
 [4]]


In [ ]:
# copying slice of an array = copy()

"""normally modifying an element of the slice of an array also modifies the original array
 because both are pointing to same memory location
this is why we use copy() method to create a copy of the slice so that original array is not modified"""


import numpy as np
arr = np.array([10,20,30,40,50])

arr_slice = arr[1:4].copy() # creating a copy of the slice from index 1 to index 3
arr_slice[1] = 100
print(arr_slice) # modified slice
print(arr) # original array remains unchanged



In [ ]:
# advanced indexing

lst = np.array([ 10 , 20 ,30 ,40 ]) 

values = lst[[0,3,1]]

print(values)
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr>1])
arr2[arr2>2] = 0 

print(arr2)
print(arr2)
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration 
print(arr3)
for i in np.nditer(arr3):
    print(i)