1- reshaping a matrix by interchanging row and col size
2- change dimention of arrays ex:1D to 2D
3- concetanation of arrays
4- transpose matrix
5- split array equally and unequally
6- arithmetic operation between elements of two array
7- triginometric functions(sin,cos,tan...)
8- logarithmic functions(logbase10, logbase2, sqrt)
9- summation and cumulative sum
10- broadcasting= arith operation of a single number or a vector to each element of an array
11- logical func between elements of 2 array , all(),any()
12- sorting in nd array
13- searching in nd array
14- index of max and min value
15- counting
16- loading data from a csv file and doing statistical operation 
17- matrix multiplication

In [5]:
# reshaping a matrix using numpy
import numpy as np

arr= np.random.randint(1,100, size=(5,10)) # 5 featuires and 10 samples (5 row and 10 columns )
print(arr.shape)

b= arr.reshape(10,5) # reshaping to 10 features and 5 samples (10 rows and 5 columns)
print( b.shape)

(5, 10)
(10, 5)


In [ ]:
# change dimention of a matrix without changing its data

import numpy as np
arr= np.random.randint(1,50, size=(5,10))
print(arr)


c= arr.flatten() # converting to 1D array
print(c)

# column wise flattening
d= arr.flatten(order='F') # converting to 1D array column wise F means column wise
print(d)

# row wise flattening
e= arr.flatten(order='C') # converting to 1D array row wise C means row wise
print(e)

[[16 94 90 16 63 84 94 53 84 87]
 [49 66 66 30 71 58 42 77 49  5]
 [92 38  8 58  6 41 66 28 96 16]
 [ 4 75 56 17 84 80 39 84 21 80]
 [87 33 25 96 49 84  3  8 27 31]]
[16 94 90 16 63 84 94 53 84 87 49 66 66 30 71 58 42 77 49  5 92 38  8 58
  6 41 66 28 96 16  4 75 56 17 84 80 39 84 21 80 87 33 25 96 49 84  3  8
 27 31]
[16 49 92  4 87 94 66 38 75 33 90 66  8 56 25 16 30 58 17 96 63 71  6 84
 49 84 58 41 80 84 94 42 66 39  3 53 77 28 84  8 84 49 96 21 27 87  5 16
 80 31]
[16 94 90 16 63 84 94 53 84 87 49 66 66 30 71 58 42 77 49  5 92 38  8 58
  6 41 66 28 96 16  4 75 56 17 84 80 39 84 21 80 87 33 25 96 49 84  3  8
 27 31]


In [ ]:
# concatenation of two arrays ,
# for row wise concatenation both the arrays must have same number of columns and 
# for column wise concatenation both the arrays must have same number of rows
import numpy as np

a = np.random.randint(1,20, size=(2,3))
b = np.random.randint(1,20, size=(2,3))
print(a)
print(b)

# row wise
c= np.concatenate((a,b), axis=0) # axis=0 means row wise
print(c)    

# column wise
d= np.concatenate((a,b), axis=1) # axis=1 means column wise
print(d)

[[ 3  5  3]
 [13 14 15]]
[[ 7  3  9]
 [18  3 12]]
[[ 3  5  3]
 [13 14 15]
 [ 7  3  9]
 [18  3 12]]
[[ 3  5  3  7  3  9]
 [13 14 15 18  3 12]]


In [1]:
# transpose matrix , columns become rows and rows become columns
import numpy as np
mat = np.array([[1,2,3],
                [4,5,6]
                ])

transpose = mat.T
print(transpose)    


[[1 4]
 [2 5]
 [3 6]]


In [3]:
# splitting array
import numpy as np

arr= np.random.randint(1,100, size=(10,))
print(arr)

# splitting unequally
unequal_split = np.array_split(arr, 3) # we cant equally divide 10 elements into 3 parts so we use array_split
print(unequal_split)


# splitting equally
equal_split = np.split(arr, 2) # we can equally divide 10 elements into 2 parts so we use split
print(equal_split)



[60 15 47 48 25 19 41  6 89 68]
[array([60, 15, 47, 48], dtype=int32), array([25, 19, 41], dtype=int32), array([ 6, 89, 68], dtype=int32)]
[array([60, 15, 47, 48, 25], dtype=int32), array([19, 41,  6, 89, 68], dtype=int32)]


In [6]:
# add , sub , mult, div  elements of two arrays
import numpy as np

a = np.array([4,5,6])
b = np.array([1,2,3])
c= a + b
print(c)

d= a - b
print(d)

e= a * b
print(e)

f= a / b
print(f)

g = a%b
print(g)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[0 1 0]


In [9]:
# trigonometric functions in numpy
# sin  , cos , tan and the values are in radians
# radian to degree conversion : radian = degree * (pi/180)
# degree to radian conversion : degree = radian * (180/pi)

import numpy as np

x = np.array([0,30,45,60,90])

# sine
sin_val = np.sin(x)
print(sin_val)

# cosine
cos_val = np.cos(x)
print(cos_val)

# tangent
tan_val = np.tan(x)
print(tan_val)

# radian to degree 
radian = np.rad2deg(x)
print(radian)

# degree to radian
degree = np.deg2rad(x)
print(degree)

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]
[   0.         1718.87338539 2578.31007809 3437.74677078 5156.62015618]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [ ]:
# logarithmic functions
import numpy as np

x = np.array([10,20,30,100])

# log base 10
log_val = np.log10(x) 
print(log_val)

# log base 2
log2_val = np.log2(x)
print(log2_val)

# square root
sqrt_val = np.sqrt(x)
print(sqrt_val)

[1.         1.30103    1.47712125 2.        ]


In [12]:
# sums
import numpy as np

# summation
x = np.array([10,8,16,20])
sums = np.sum(x)
print(sums)

# cumulative sum
cum_sum = np.cumsum(x)
print(cum_sum)


54
[10 18 34 54]


In [ ]:
# broadcasting 
# adding , subtracting ,squaring , multiplying or dividing a single number to each element of an array
# adding a vector to each row of a matrix 
import numpy as np

a = np.array([1,3,9])


# adding 5 to each element of array 
res_1 = a + 5  
print(res_1)

# squaring each element of array
res_2 = a**2  
print(res_2)


# adding a vector to each row of a matrix , culumn size must be same
mat = np.array([[1,2,3],
                [4,5,6]]) # matrix is 2d array

vec = np.array([1,0,1]) # vector is 1d array

res = mat + vec  
print(res)



[ 6  8 14]
[ 1  9 81]
[[2 2 4]
 [5 5 7]]


In [17]:
# logical functions
# element wise comparison between two arrays
# all() = check if all elements are true
# any() = check if any element is true

import numpy as np

a = np.array([2,2,5,4,5])
b = np.array([1,0,6,0,5])

greaterthan = a>b
print(greaterthan)

lessthan = a<b
print(lessthan)

equalto = a==b
print(equalto)

# check if all elements are true
print( np.all(greaterthan) ) 

# check if any element is true
print( np.any(lessthan) ) 




[ True  True False  True False]
[False False  True False False]
[False False False False  True]
False
True


In [ ]:
# 1D array sorting
# inplace sorting = sorts the original array
# outplace sorting = returns a new sorted array , original array remains unchanged

import numpy as np
arr = np.array([5,2,8,1,4])
z = arr.copy()


# inplace sorting = sort()
print(z)
z.sort()
print(z)  # original array is changed


# outplace sorting = np.sort()

sorted_arr = np.sort(arr)
print(sorted_arr) 
print(arr)  # original array remains unchanged


[5 2 8 1 4]
[1 2 4 5 8]
[1 2 4 5 8]
[5 2 8 1 4]


In [ ]:
# 2D array sorting
# row wise sorting = sort each row individually (axis=1)
# column wise sorting = sort each column individually (axis=0)

mat = np.array([[10,3,5],
                [8,4,9]])

horizontal_sort = np.sort(mat, axis=1) # row wise sorting
print(horizontal_sort)


vertical_sort = np.sort(mat, axis=0) # column wise sorting
print(vertical_sort)


[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


In [27]:
# searching elements in 1D array 
# np.where(condition,x,y) = if x is true return x else return y
import numpy as np

# return index of all occurrences of 8 in the array
arr = np.array([10,8,16,10])
indices = np.where(arr == 8) 
print(indices) 


# return index of all occurrences of elements greater than 8
indices_gt = np.where(arr > 8)
print(indices_gt)

# np.where with x and y , return array
replace = np.where(arr > 8, arr, -1) # if condition is true return the element of arr else return replace it with -1
print(replace)

(array([1]),)
(array([0, 2, 3]),)
[10 -1 16 10]


In [ ]:
# searching elements in 2D array
import numpy as np

arr_2d = np.array([[10,3,5],
                   [8,4,9]])
indices_2d = np.where(arr_2d > 8)
print(indices_2d)


replace_2d = np.where(arr_2d > 8, arr_2d, -1)
print(replace_2d)




(array([0, 1]), array([0, 2]))
[[10 -1 -1]
 [-1 -1  9]]


In [30]:
# find index of max value and min value in an array

import numpy as np
arr = np.array([10,8,16,20,5])

max_index = np.argmax(arr)  # index of max value
print(max_index)

min_index = np.argmin(arr)  # index of min value
print(min_index)

3
4


In [34]:
# counting

import numpy as np

a=np.random.randint(1,100, size=(100,))

# count numbers that are greater than 50
count_gt_50 = np.count_nonzero(a > 50)
print(count_gt_50)


# return array that contains count of each unique element in the array
# will first give array that contains all unique elements and then their counts
unique = np.unique(a, return_counts=True)
print(unique)


50
(array([ 1,  2,  8,  9, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 24, 25, 26,
       28, 29, 30, 32, 33, 34, 35, 36, 37, 39, 43, 44, 46, 47, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 59, 60, 64, 67, 70, 71, 73, 74, 75, 76, 78,
       79, 80, 81, 82, 83, 85, 88, 90, 93, 94, 97, 98], dtype=int32), array([2, 4, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 3, 1, 2, 3, 3, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 4, 1, 3,
       4, 4, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 3, 2, 1, 1]))


In [43]:
# loading data from a csv file
import numpy as np

# this funnction loads data from student_scores.csv file and delimiter is comma means values are separated by comma
# skip the non numerical values written as nan in first row (header) by adding skip_header=1 after delimiter
data = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=1)
print(data)


# finding max ,min ,avg, median, standard deviation marks for subject in first column
math_marks = data[::,:1]  # bring out all rows of first colum
print(math_marks)

max_math = np.max(math_marks) # find max value
print(max_math)

min_math = np.min(math_marks) # find min value
print(min_math)

avg_math = np.mean(math_marks) # find average value
print(avg_math)

median_math = np.median(math_marks) # find median value
print(median_math)

std_math = np.std(math_marks) # find standard deviation value
print(std_math)



[[78. 92. 99.]
 [91. 41. 55.]
 [68. 63. 54.]
 [54. 83. 86.]
 [82. 69. 90.]
 [47. 77. 83.]
 [60. 41. 94.]
 [78. 99. 91.]
 [97. 60. 96.]
 [58. 72. 42.]]
[[78.]
 [91.]
 [68.]
 [54.]
 [82.]
 [47.]
 [60.]
 [78.]
 [97.]
 [58.]]
97.0
47.0
71.3
73.0
15.678328992593567


In [ ]:
# matrix multiplication

import numpy as np

# DOT product
# column size of first matrix must be equal to row size of second matrix
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7,8],
              [9,10],
              [11,12]])
result = np.dot(a,b)
print(result)


# trace
# summation of diagonal elements of a square matrix
print(np.trace(b))  


# determinant
sq_mat = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
det = np.linalg.det(sq_mat)
print(det)


# rank of a matrix
rank_sq = np.linalg.matrix_rank(sq_mat)
print(rank_sq)


[[ 58  64]
 [139 154]]
17
0.0
2
